num_steps: 50000
num_saves: 5
action_horizon: 16
modality_keys: []
output_dir: /raid/datasets/trossen/results
model_name: gr00t_tower4_70_vague_long
val_step_size: 500
resume_from_checkpoint: True # True or False